[manifest]
version = "1.0.0"
dump_lua = true
priority = -12

# replace int literals with floats
[[patches]]
[patches.regex]
target = "GLSL_ES_PATCHES.fs"
pattern = '''([^\w\d.]\d+)([^\w\d.])'''
payload = '$1.$2'
position = 'at'

# swap out type "int" for "float" in case a now-float literal is attached to an explicit type
[[patches]]
[patches.regex]
target = "GLSL_ES_PATCHES.fs"
pattern = '''([\s(\{])int([\s(\[])'''
payload = '''$1 float$2'''
position = 'at'