[manifest]
version = "1.0.0"
dump_lua = true
priority = -10

[[patches]]
[patches.pattern]
target = 'engine/text.lua'
pattern = "if self.config.bump then letter.offset.y = (G.SETTINGS.reduced_motion and 0 or 1)*self.bump_amount*math.sqrt(self.scale)*7*math.max(0, (5+self.bump_rate)*math.sin(self.bump_rate*G.TIMERS.REAL+200*k) - 3 - self.bump_rate) end"
position = "after"
payload = '''if self.config.text_effect and SMODS.DynaTextEffects[self.config.text_effect] and type(SMODS.DynaTextEffects[self.config.text_effect].func) == "function" then
    SMODS.DynaTextEffects[self.config.text_effect].func(self, k, letter) -- k is index
end'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'functions/misc_functions.lua'
pattern = "          local _float, _silent, _pop_in, _bump, _spacing = nil, true, nil, nil, nil"
position = "after"
payload = '''local text_effects'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'functions/misc_functions.lua'
pattern = "            _bump = true; _spacing = 1"
position = "after"
payload = '''elseif SMODS.DynaTextEffects[part.control.E] then
    text_effects = part.control.E'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'functions/misc_functions.lua'
pattern = "            spacing = _spacing,"
position = "after"
payload = '''text_effect = text_effects,'''
match_indent = true