[manifest]
version = "1.0.0"
dump_lua = true
priority = -10

## colour argument fix
# create_tabs()
[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
pattern = '''tab_buttons[#tab_buttons+1] = UIBox_button({id = 'tab_but_'..(v.label or ''), ref_table = v, button = 'change_tab', label = {v.label}, minh = 0.8*args.scale, minw = 2.5*args.scale, col = true, choice = true, scale = args.text_scale, chosen = v.chosen, func = v.func, focus_args = {type = 'none'}})'''
position = 'at'
payload = '''tab_buttons[#tab_buttons+1] = UIBox_button({id = 'tab_but_'..(v.label or ''), ref_table = v, button = 'change_tab', label = {v.label}, minh = 0.8*args.scale, minw = 2.5*args.scale, col = true, choice = true, scale = args.text_scale, chosen = v.chosen, func = v.func, colour = args.colour, focus_args = {type = 'none'}})'''
match_indent = true

# UIElement:draw_self()
[[patches]]
[patches.pattern]
target = 'engine/ui.lua'
pattern = '''love.graphics.polygon("fill", get_chosen_triangle_from_rect(self.layered_parallax.x, self.layered_parallax.y, self.VT.w*G.TILESIZE, self.VT.h*G.TILESIZE, self.config.chosen == 'vert'))'''
position = 'before'
payload = '''love.graphics.setColor(self.config.colour)'''
match_indent = true

# Game:draw()
# Draw dropdowns right before G.OVERLAY_MENU if the dropdown was created while G.OVERLAY_MENU didn't exist
[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = '''
if (self.OVERLAY_MENU) or (not self.F_HIDE_BG) then
'''
position = 'before'
payload = '''
for k, v in pairs(self.I.DROPDOWN) do
    if v.parent == G.ROOM_ATTACH then
        love.graphics.push()
        v:translate_container()
        v:draw()
        love.graphics.pop()
    end
end
'''
match_indent = true

# Draw dropdowns right before the drag target if the dropdown was created while G.OVERLAY_MENU exists
[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = '''
if self.CONTROLLER.dragging.target and self.CONTROLLER.dragging.target ~= self.CONTROLLER.focused.target then
'''
position = 'before'
payload = '''
for k, v in pairs(self.I.DROPDOWN) do
    if v.parent == G.OVERLAY_MENU then
        love.graphics.push()
        v:translate_container()
        v:draw()
        love.graphics.pop()
    end
end
'''
match_indent = true

# Game:set_globals()
# Add G.I.DROPDOWN
[[patches]]
[patches.pattern]
target = 'globals.lua'
pattern = '''
UIBOX = {},
'''
position = 'after'
payload = '''
DROPDOWN = {},
'''
match_indent = true

## multiple text input fix
# create_text_input()
[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
pattern = '''args.current_prompt_text = '''''
position = 'after'
payload = '''args.id = args.id or "text_input"'''
match_indent = true
[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
pattern = '''ui_letters[#ui_letters+1] = {n=G.UIT.T, config={ref_table = args, ref_value = 'current_prompt_text', scale = args.text_scale, colour = lighten(copy_table(args.colour), 0.4), id = 'prompt'}}'''
position = 'at'
payload = '''ui_letters[#ui_letters+1] = {n=G.UIT.T, config={ref_table = args, ref_value = 'current_prompt_text', scale = args.text_scale, colour = lighten(copy_table(args.colour), 0.4), id = args.id..'_prompt'}}'''
match_indent = true
[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
pattern = '''ui_letters[i] = {n=G.UIT.T, config={ref_table = text.letters, ref_value = i, scale = args.text_scale, colour = G.C.UI.TEXT_LIGHT, id = 'letter_'..i}}'''
position = 'at'
payload = '''ui_letters[i] = {n=G.UIT.T, config={ref_table = text.letters, ref_value = i, scale = args.text_scale, colour = G.C.UI.TEXT_LIGHT, id = args.id..'_letter_'..i}}'''
match_indent = true
[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
pattern = '''ui_letters[#ui_letters+1] = {n=G.UIT.B, config={r = 0.03,w=0.1, h=0.4, colour = position_text_colour, id = 'position', func = 'flash'}}'''
position = 'at'
payload = '''ui_letters[#ui_letters+1] = {n=G.UIT.B, config={r = 0.03,w=0, h=0.4, colour = position_text_colour, id = args.id..'_position', func = 'flash'}}'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
pattern = '''{n=G.UIT.C, config={align = "cm", draw_layer = 1, colour = G.C.CLEAR}, nodes = {'''
position = 'at'
payload = '''{n=G.UIT.C, config={align = "cm", colour = G.C.CLEAR}, nodes = {'''
match_indent = true
[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
pattern = '''{n=G.UIT.C, config={id = 'text_input', align = "cm", padding = 0.05, r = 0.1, draw_layer = 2, hover = true, colour = args.colour,minw = args.w, min_h = args.h, button = 'select_text_input', shadow = true}, nodes={'''
position = 'at'
payload = '''{n=G.UIT.C, config={id = args.id, align = "cm", padding = 0.05, r = 0.1, hover = true, colour = args.colour,minw = args.w, min_h = args.h, button = 'select_text_input', shadow = true}, nodes={'''
match_indent = true

# G.FUNCS.select_text_input
[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
pattern = '''G.CONTROLLER.text_input_hook = e.children[1].children[1]'''
position = 'after'
payload = '''G.CONTROLLER.text_input_id = e.config.id'''
match_indent = true

# G.FUNCS.paste_seed
[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
pattern = '''G.CONTROLLER.text_input_hook = e.UIBox:get_UIE_by_ID('text_input').children[1].children[1]'''
position = 'after'
payload = """G.CONTROLLER.text_input_id = 'text_input'"""
match_indent = true

# G.FUNCS.flash
[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
pattern = '''if G.CONTROLLER.text_input_hook then'''
position = 'at'
payload = '''if G.CONTROLLER.text_input_hook and G.CONTROLLER.text_input_id == e.config.id:sub(1,string.len(G.CONTROLLER.text_input_id)) then'''
match_indent = true

# TRANSPOSE_TEXT_INPUT()
[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
pattern = '''if hook.children[i].config.id == 'position' then'''
position = 'at'
payload = '''if hook.children[i].config.id == G.CONTROLLER.text_input_id..'_position' then'''
match_indent = true
[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
pattern = '''local real_letter = hook.children[position_child+dir].config.id:sub(1, 7) == 'letter_' and hook.children[position_child+dir].config.text ~= '''''
position = 'at'
payload = '''local real_letter = hook.children[position_child+dir].config.id:sub(1, 8+string.len(G.CONTROLLER.text_input_id)) == G.CONTROLLER.text_input_id..'_letter_' and hook.children[position_child+dir].config.text ~= '''''
match_indent = true

# GET_TEXT_FROM_INPUT()
[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
pattern = '''if hook.children[i].config and hook.children[i].config.id:sub(1, 7) == 'letter_' and hook.children[i].config.text ~= '' then'''
position = 'at'
payload = '''if hook.children[i].config and hook.children[i].config.id:sub(1, 8+string.len(G.CONTROLLER.text_input_id)) == G.CONTROLLER.text_input_id..'_letter_' and hook.children[i].config.text ~= '' then'''
match_indent = true

# remove hardcoded shop selection limit
[[patches]]
[patches.pattern]
target = "cardarea.lua"
pattern = "if self.highlighted[1] then"
position = "at"
payload = "if #self.highlighted >= self.config.highlighted_limit then"
match_indent = true

# Deck unlock popup shows custom unlock descriptions
# create_UIBox_deck_unlock()
[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
pattern = "if deck_center.unlock_condition.type == 'win_deck' then"
position = "before"
payload = """
if deck_center.check_for_unlock and type(deck_center.check_for_unlock) == "function" then
    local loc_args = {}
    local key_override
    if deck_center.locked_loc_vars and type(deck_center.locked_loc_vars) == 'function' then
        local res = deck_center:locked_loc_vars() or {}
        loc_args = res.vars or {}
        key_override = res.key
    end
    localize{type = 'unlocks', key = key_override or deck_center.key, set = "Back", nodes = deck_criteria, vars = loc_args, default_col = G.C.WHITE, shadow = true}
end
"""
match_indent = true

## UIBox shaders
# UIElement:draw_pixellated_rect()
[[patches]]
[patches.pattern]
target = "engine/ui.lua"
pattern = '''love.graphics.polygon((_type == 'line' or _type == 'line_emboss') and 'line' or "fill", self.pixellated_rect[_type].vertices)'''
position = "at"
payload = '''
    local function _draw()
        -- don't duplicate the line
        love.graphics.polygon((_type == 'line' or _type == 'line_emboss') and 'line' or "fill", self.pixellated_rect[_type].vertices)
    end

    local function _draw_layer(shader, send)
        local args = {
            G.TIMERS.REAL/28,
            G.TIMERS.REAL
        }
        
        if shader == "none" or shader == "dissolve" then
            _draw()
            return
        elseif send then
            for _, v in ipairs(send) do
                local val = v.val or (v.func and v.func(self)) or v.ref_table[v.ref_value]
                -- TARGET: Convert v.val to a number if your mod adds an alternate number data type (ala Talisman)

                G.SHADERS[shader]:send(v.name, val)
            end
        elseif shader == "vortex" then
            G.SHADERS['vortex']:send('vortex_amt', G.TIMERS.REAL - (G.vortex_time or 0))
        else
            local key = SMODS.Shaders[shader].original_key
            local tile_scale = G.TILESCALE*G.TILESIZE*G.CANV_SCALE

            G.SHADERS[shader]:send(key, args)
            G.SHADERS[shader]:send("uie_details", {self.VT.x * tile_scale, self.VT.y * tile_scale, self.VT.w * tile_scale, self.VT.h * tile_scale})
            G.SHADERS[shader]:send("uie_scale", self.VT.scale)
            G.SHADERS[shader]:send("uie_rot", self.VT.r)
        end

        local p_shader = SMODS.Shader.obj_table[shader or 'dissolve']
        if p_shader and type(p_shader.send_vars) == "function" then
            local sh = G.SHADERS[shader or 'dissolve']
            local send_vars = p_shader.send_vars(self)
        
            if type(send_vars) == "table" then
                for key, value in pairs(send_vars) do
                    sh:send(key, value)
                end
            end
        end

        love.graphics.setShader(G.SHADERS[shader], G.SHADERS[shader])
        _draw()
        love.graphics.setShader()

        love.graphics.setShader(G.SHADERS[shader], G.SHADERS[shader])
        _draw()
        love.graphics.setShader()
    end

    if self.config.shader then
        -- simple single shader
        if type(self.config.shader) == "string" then
            _draw_layer(self.config.shader)

        -- more complex shader calls
        elseif type(self.config.shader) == "table" then
            -- one shader pass with a custom send
            if self.config.shader.shader then
                _draw_layer(self.config.shader.shader, self.config.shader.send)

            -- list of shaders
            elseif #shader > 0 then
                for _, v in ipairs(self.config.shader) do
                    if type(v) == "string" then
                        _draw_layer(v.shader)
                    elseif type(v) == "table" then
                        _draw_layer(v.shader, v.send)
                    end
                end
            end
        end

    -- no shader
    else
        _draw()
    end
'''
match_indent = true
